apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004 # port on the node/worker node/minikube node on which application will be accessible
  selector:
    app: myapp

